[[redirects]]
  from = "/marvel-history"
  to = "https://marvel-history.netlify.app/marvel-history/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/marvel-history/*"
  to = "https://marvel-history.netlify.app/marvel-history/:splat"
  status = 200
  force = true
